<a href="https://colab.research.google.com/github/pthkbs123/SkillTreePython-DataAnalysis/blob/main/01.%EB%8D%B0%EC%9D%B4%ED%84%B0%EB%B6%84%EC%84%9D%EA%B8%B0%EC%B4%88/05_NumPy-%EB%B0%B0%EC%97%B4%EC%9D%98%EC%97%B0%EC%82%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# CH05 Numpy  - 배열의 연산

---
* 날짜: 2022-04-12
* 이름: 박태현



```
import numpy as np
```




In [ ]:
import numpy as np

---
### **(1) 산술 연산(Arithmetic Operators)**
---

|연산자|범용함수|설명|
|--|--|--|
|+|`np.add`|덧셈|
|-|`np.substract`|뺄셈|
|-|`np.negative`|단항음수|
|*|`np.multiply`|곱셈|
|/|`np.divide`|나눗셈|
|//|`np.floor_divide`|나눗셈 내림|
|**|`np.power`|지수 연산|
|%|`np.mod`|나머지 연산|

파이썬의 수치자료형에서 사용하는 모든 연산을 넘파이 배열에서 사용할 수 있습니다. 

리스트에서는 불가능했던 배열간의 덧셈도 아래와 같이 사용 가능합니다.

```
a = np.array([1,2,3])
b = np.array([-1,2,-3])
a*b
```



In [ ]:
a = np.array([1,2,3])
b = np.array([-1,2,-3])
a*b, np.multiply(a,b)

(array([-1,  4, -9]), array([-1,  4, -9]))


#### **|  브로드캐스팅 (Broadcasting)**

NumPy의 배열 연산은 벡터화(vectorized) 연산을 사용합니다. 브로드 캐스팅은 배열 각 요소에 대한 반복적인 계산을 효율적으로 수행합니다.


<p align='center'>
<img src=https://github.com/yebiny/SkillTreePython-DataAnalysis/blob/main/imgs/ch0105-01.png?raw=true width=560>
</p>

In [ ]:
x = np.arange(1,10).reshape(3,3)
y = np.full([3,3],2)
y_2 = np.array([2,2,2])

print(x * y)
print(x * y_2)
print(x * 2)
# 셋 다 같은 결과. 직관적으로 사용 가능

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


---
### **(2) 수학 관련 함수**
---





#### **| 절대값 함수 (Absolute Function)**





* `np.absolute(n)` = `np.abs(n)` : `n`의 절대값 반환

```
print(b)
np.abs(b)
```


In [ ]:
print(b)
np.abs(b)

[-1  2 -3]


array([1, 2, 3])

#### **| 제곱/제곱근 함수**

* `np.square(n)`: `n`의 제곱을 반환
* `np.sqrt(n)` : `n`의 제곱근을 반환

```
n = 25
print(np.square(n), np.sqrt(n))
```

In [ ]:
n = 25
print(np.square(n), np.sqrt(n))

625 5.0


#### **| 지수/로그 함수**

* `np.exp(n)` : 자연상수 `e`(=~2.71..)의 `n` 제곱을 반환
* `np.exp2(n)` : 상수 `2`의 `n` 제곱을 반환


```
[np.exp2(n) for n in range(10)]
```







In [ ]:
[np.exp2(n) for n in range(10)]

[1.0, 2.0, 4.0, 8.0, 16.0, 32.0, 64.0, 128.0, 256.0, 512.0]


* `np.log(n)` : 밑이 `e`인 로그값을 반환합니다. 
* `np.log2(n)` : 밑이 `2`인 로그값을 반환합니다.
* `np.log10(n)` : 밑이 `10`인 로그값을 반환합니다.

```
n = [10,100,1000,10000]
np.log10(n)
```

In [ ]:
n = [10,100,1000,10000]
np.log10(n)

array([1., 2., 3., 4.])

#### **| 삼각 함수(Trigonometrical Function)**

|함수|설명|
|--|--|
|`np.sin`|사인|
|`np.cos`|코사인|
|`np.tan`|탄젠트|
|`np.arcsin`|아크 사인|
|`np.argcos`|아크 코사인|
|`np.argtan`|아크 탄젠트|
|`np.sinh`|하이퍼볼릭 사인|
|`np.cosh`|하이퍼볼릭 코사인|
|`np.tanh`|하이퍼볼릭 탄젠트|
|`np.arcsinh`|하이퍼볼릭 아크 사인|
|`np.arccosh`|하이퍼볼릭 아크 코사인|
|`np.arctanh`|하이퍼볼릭 아크 탄젠트|
|`np.deg2rad`|각도를 라디안으로 변환|
|`np.rad2deg`|라디안을 각도로 변환|
|`np.hypot`|유클리드 거리계산|

학창시절 아래 삼각함수 표를 외워본 경험이 있을 겁니다. 더이상 이를 외울 필요는 없습니다. 코드가 알아서 해줄테니까요. 값이 똑같이 나오는지 확인해 봅시다.

<p align='center'>
<img src=https://github.com/yebiny/SkillTreePython-DataAnalysis/blob/main/imgs/ch0105-02.png?raw=true width=500>
</p>

```
n = 0
np.sin(n), np.cos(n), np.tan(n)
```

In [ ]:
n = 0
np.sin(n), np.cos(n), np.tan(n)

(0.0, 1.0, 0.0)

#### **| 집계 함수(Aggregate Functions)**

|함수|설명|
|--|--|
|`np.sum()`|배열 내 합을 반환|
|`np.cumsum()`|배열 내 누적합 반환|
|`np.prod()`|배열 내 곱 반환|
|`np.diff()`|배열 내 차 반환|
|`np.min()`|최소값 반환|
|`np.max()`|최대값 반환|
|`np.mean()`|평균 반환|
|`np.std()`|표준편차 반환|
|`np.var()`|분산 반환|
|`np.median()`|중앙값 반환|
|`np.argmin()`|최소값 인덱스 반환|
|`np.argmax()`|최소값 인덱스 반환|


```
print(a)
print('누적합: ',np.cumsum(a))
print('곱: ',np.prod(a))
print('차: ',np.diff(a))
print('중앙값: ',np.median(a))
```

In [ ]:
print(a)
print('누적합: ',np.cumsum(a))
print('곱: ',np.prod(a))
print('차: ',np.diff(a))
print('중앙값: ',np.median(a))

[1 2 3]
누적합:  [1 3 6]
곱:  6
차:  [1 1]
중앙값:  2.0


머신러닝에서 자주 사용되는 함수는 `np.argmax`입니다. `np.argmax`는 최대값의 인덱스를 반환하는데요, 최대값 자체가 아닌 인덱스가 언제 필요할까요?

예시를 들어 봅시다. `y`에 카드 이름이, `x`에는 각 카드가 뽑힐 확률이 들어 있습니다. 뽑힐 확률이 가장 높은 카드를 아래와 같이 구할 수 있습니다.

```
x = [0.1, 0.2, 0.6, 0.1]
y = ['a', 'b', 'c', 'd']
idx = np.argmax(x)
print(y[idx]) # 팬시 인덱싱
```

In [ ]:
x = [0.1, 0.2, 0.6, 0.1]
y = ['a', 'b', 'c', 'd']
idx = np.argmax(x)
print(y[idx]) # 팬시 인덱싱

c


---
### **(3) 벡터/행렬 연산**
---

|함수|설명|
|--|--|
|`np.matmul()`|=`@`, 행렬곱|
|`np.dot()`|내적|
|`np.prod()`|외적|




* `np.matmul(a1, a2)` : 배열 `a1`과 `a2`의 행렬곱을 수행합니다. 

일반적인 행렬곱을 `matmul`을 통해서 할 수 있습니다. 

```
A = np.array([[1,2],
              [0,1]])
B = np.array([[1,0],
              [0,1]])
print(np.matmul(A,B))
print(A@B)
```


In [ ]:
A = np.array([[1,2],
              [0,1]])
B = np.array([[1,0],
              [0,1]])
print(np.matmul(A,B))
print(A@B)

[[1 2]
 [0 1]]
[[1 2]
 [0 1]]


* `np.dot(a1, a2)`: 배열 `a1`과 `a2`의 벡터 내적을 수행합니다.

벡터 내적은 벡터 내 같은 인덱스의 값을 곱하고 모두 더한 것입니다.

```
print(a, b)
print(sum(a*b))
print(np.dot(a,b))
```




In [ ]:
print(a, b)
print(sum(a*b))
print(np.dot(a,b))

[1 2 3] [-1  2 -3]
-6
-6


---
### **(4) 비교 연산**
---

비교 연산자를 이용하면 `boolean` 값으로 이루어진 배열을 반환합니다.





#### **| 값 비교**


|연산자|비교 범용 함수|
|--|--|
|`==`|`np.equal`|
|`!=`|`np.not_equal`|
|`<`| `np.less`|
|`<=`|`np.less_equal`|
|`>`| `np.greater`|
|`>=`|`np.greater_equal`|

```
print(a)
print(b)
a==b, a<b, a>b
```

In [ ]:
print(a)
print(b)
a==b, a<b, a>b

[1 2 3]
[-1  2 -3]


(array([False,  True, False]),
 array([False, False, False]),
 array([ True, False,  True]))


#### **| 예외값 비교**



|함수|설명|
|--|--|
|`np.isinf`|`inf` 값이면 `True`, 아니면 `False`|
|`np.isfinite`|`inf, nan` 값이면 `False`, 아니면 `True`|
|`np.isnan`|`nan` 값이면 `True`, 아니면 `False`|

```
a = [np.inf, np.nan, 0]
print(np.isinf(a))
print(np.isfinite(a))
print(np.isnan(a))
```

In [ ]:
a = [np.inf, np.nan, 0]
print(np.isinf(a))
print(np.isfinite(a))
print(np.isnan(a))

[ True False False]
[False False  True]
[False  True False]


#### **| 논리 연산자**

|함수|설명|
|--|--|
|`np.all()`|모두 `True`일때 `True` 반환|
|`np.any()`|모두 `False`일때 `False` 반환|

파이썬의 논리 연산자와 동일 합니다. 아래와 같이 숫자 자료형을 바로 넣으면 0 일 때는 `False`, 그 외에는 `True`로 인식하여 연산이 진행됩니다.

```
a = [1,0,1,1,0]
np.all(a), np.any(a)
```

In [ ]:
a = [1,0,1,1,0]
np.all(a), np.any(a)

(False, True)

---
### **(5) 정렬**
---


|함수|설명|
|--|--|
|`np.sort()`|오름차순 정렬|
|`np.argsort()`|index 정렬|
|`np.partition()`|`k`개의 작은값 반환|


* `np.sort(a, axis=axis)` : 배열 `a`를 오름차순으로 정렬합니다. 

```
np.random.seed(42);a = np.random.randint(0,12,(3,4))
print(a)
print('axis=0: 위에서 아래로 정렬')
print(np.sort(a, axis=0))
print('axis=1: 좌에서 우로 정렬')
print(np.sort(a, axis=1))
```


In [ ]:
np.random.seed(42);a = np.random.randint(0,12,(3,4))
print(a)
print('axis=0: 위에서 아래로 정렬')
print(np.sort(a, axis=0))
print('axis=1: 좌에서 우로 정렬')
print(np.sort(a, axis=1))

[[ 6  3 10  7]
 [ 4  6  9  2]
 [ 6 10 10  7]]
axis=0: 위에서 아래로 정렬
[[ 4  3  9  2]
 [ 6  6 10  7]
 [ 6 10 10  7]]
axis=1: 좌에서 우로 정렬
[[ 3  6  7 10]
 [ 2  4  6  9]
 [ 6  7 10 10]]


* `np.argsort(a, axis=axis)` : 배열 `a`를 오름차순 정렬하는  인덱스를 반환

위에서 배웠던 `np.argmax`와 마찬가지로 팬시 인덱싱에서 유용하게 사용됩니다. 

아래와 같이 월별(x) 판매수(y)가 주어졌을 때 판매수 순으로 정렬하고자 합니다. 

```
x = np.array(['1월', '2월', '3월'])
y = np.array([500,230,350])
sort_idx = np.argsort(y)
print(sort_idx)
x[sort_idx][::-1] # 팬시 인덱싱
```

In [ ]:
x = np.array(['1월', '2월', '3월'])
y = np.array([500,230,350])
sort_idx = np.argsort(y)
print(sort_idx)
x[sort_idx][::-1] # 팬시 인덱싱

[1 2 0]


array(['1월', '3월', '2월'], dtype='<U2')

In [ ]:
x[sort_idx][::-1]

array(['1월', '3월', '2월'], dtype='<U2')

## 문제풀이
---

**예제 01**

아래 그림에 있는 산술연산을 각각 코드로 구현하세요

<p align='center'>
<img src=https://github.com/yebiny/SkillTreePython-DataAnalysis/blob/main/imgs/ch0105-03.png?raw=true width=400>
</p>


In [ ]:
a01 = np.array([1,2,3])
print(a01 + 2)
print(a01 - 2)
print(a01 % 2)
print(a01 ** 2)

[3 4 5]
[-1  0  1]
[1 0 1]
[1 4 9]


**예제 02**


아래는 `sum`의 용례를 그림으로 표현한 것입니다. 각 경우에 대해 코드로 구현하세요.

<p align='center'>
<img src=https://github.com/yebiny/SkillTreePython-DataAnalysis/blob/main/imgs/ch0105-04.png?raw=true width=460>
</p>


In [ ]:
a02 = np.array([[1,2,3],[1,2,3]])

In [ ]:
a02.sum(), a02.sum(axis=0),a02.sum(axis=1)

(12, array([2, 4, 6]), array([6, 6]))

**예제 03**

위와 똑같은 방법으로 3가지 경우에 대해 `min()`을 수행하세요

In [ ]:
a02.min(), a02.min(axis = 0), a02.min(axis = 1)

(1, array([1, 2, 3]), array([1, 1]))

**예제 04**

위와 똑같은 방법으로 3가지 경우에 대해 `argmax()`을 수행하세요

In [ ]:
a02.argmax(), a02.argmax(axis=0), a02.argmax(axis=1)

(2, array([0, 0, 0], dtype=int64), array([2, 2], dtype=int64))

**예제 05**

위와 똑같은 방법으로 3가지 경우에 대해 `std()`을 수행하세요

In [ ]:
a02.std(), a02.std(axis=0), a02.std(axis=1)

(0.816496580927726, array([0., 0., 0.]), array([0.81649658, 0.81649658]))

**예제 06**

아래는 `any`의 용례를 그림으로 표현한 것입니다. 각 경우에 대해 코드로 구현하고, 왜 이런 결과가 나오는지 정리하세요.


<p align='center'>
<img src=https://github.com/yebiny/SkillTreePython-DataAnalysis/blob/main/imgs/ch0105-05.png?raw=true width=580>
</p>


In [ ]:
print(np.any(a02>2))
print(np.any(a02>2, axis=0))
print(np.any(a02>2, axis=1))

# any는 1개라도 맞는게 있으면 True 반환

True
[False False  True]
[ True  True]


**예제 07**

위와 똑같은 방법으로 3가지 경우에 대해 `all()`을 수행하고, 왜 이런 결과가 나오는지 정리하세요.

In [ ]:
print(np.all(a02>2))
print(np.all(a02>2, axis=0))
print(np.all(a02>2, axis=1))

# all은 전부 맞아야 True 반환

False
[False False  True]
[False False]


**예제 08**


1에서 100까지의 랜덤값을 가지고 형태가 `(40)` 인 1차원 배열을 `a08`로 바인딩하세요

In [ ]:
np.random.seed(40);a08 = np.random.randint(1,100,size=100)
print(a08)

[71 92  8 38 57 51 66 13 72 20 32 75 56 84 60 92 74 97 50 54 74  9 53 31
 80 15 93 59 75 23  4 92 72 56 84 29 14 38 83 51 80 68 31 61 45 47 88 44
 36 99 32 83  6 81 66  8 93 42 96 89 94 26 84 59 99 71 58 58 84 86 37 64
 75 89  1  2 34 53 73 58 35 15 79 72 57 78 87 85 83 92 13 91 74 28  1 22
 95 33 52 51]


**예제 09**

`a08`에서 50보다 큰 수만 가지는 배열을 불리언 연산자를 이용해서 생성하세요.

In [ ]:
mask = a08>50
a09 = a08[mask]
a09

array([71, 92, 57, 51, 66, 72, 75, 56, 84, 60, 92, 74, 97, 54, 74, 53, 80,
       93, 59, 75, 92, 72, 56, 84, 83, 51, 80, 68, 61, 88, 99, 83, 81, 66,
       93, 96, 89, 94, 84, 59, 99, 71, 58, 58, 84, 86, 64, 75, 89, 53, 73,
       58, 79, 72, 57, 78, 87, 85, 83, 92, 91, 74, 95, 52, 51])

**예제 10**

`a08`에서 50 이하이며 3의 배수만 가지는 배열을 불리언 연산자를 이용해 생성하세요

In [ ]:
mask = a08<50
a10 = a08[mask]
a10

array([ 8, 38, 13, 20, 32,  9, 31, 15, 23,  4, 29, 14, 38, 31, 45, 47, 44,
       36, 32,  6,  8, 42, 26, 37,  1,  2, 34, 35, 15, 13, 28,  1, 22, 33])

**예제 11**

`a08`에서 90이상이거나 10이하인 수만 가지는 배열을 불리언 연산자를 이용해 생성하세요

In [ ]:
mask = (a08>=90) | (a08<=10)
a11 = a08[mask]
a11

# or 을 사용하니 에러 발생. |를 사용.

array([92,  8, 92, 97,  9, 93,  4, 92, 99,  6,  8, 93, 96, 94, 99,  1,  2,
       92, 91,  1, 95])

**예제 12**


`a08`을 shape가 `(8,5)`인 2차원 배열로 변환하고 `a12`로 바인딩 하세요.

In [ ]:
a12 = np.resize(a08,(8,5))
a12

array([[71, 92,  8, 38, 57],
       [51, 66, 13, 72, 20],
       [32, 75, 56, 84, 60],
       [92, 74, 97, 50, 54],
       [74,  9, 53, 31, 80],
       [15, 93, 59, 75, 23],
       [ 4, 92, 72, 56, 84],
       [29, 14, 38, 83, 51]])

**예제 13**


`a12`를 복사하여 `a13`으로 바인딩하고 이를 각 행 별로 정렬하세요

In [ ]:
a13 = a12.copy()
np.sort(a13, axis = 0)

array([[ 4,  9,  8, 31, 20],
       [15, 14, 13, 38, 23],
       [29, 66, 38, 50, 51],
       [32, 74, 53, 56, 54],
       [51, 75, 56, 72, 57],
       [71, 92, 59, 75, 60],
       [74, 92, 72, 83, 80],
       [92, 93, 97, 84, 84]])

**예제 14**


`a12`를 복사하여 `a14`로 바인딩하고 각 열 별로 가장 작은수 3개를 찾으세요

In [ ]:
a14 = a12.copy()
a14.sort(axis=1)
a14_find, temp = np.split(a14, [3], axis = 1)
a14_find

array([[ 8, 38, 57],
       [13, 20, 51],
       [32, 56, 60],
       [50, 54, 74],
       [ 9, 31, 53],
       [15, 23, 59],
       [ 4, 56, 72],
       [14, 29, 38]])

In [ ]:
a14_temp = np.partition(a14,0)[:,:3]
a14_temp

array([[ 8, 38, 57],
       [13, 20, 51],
       [32, 56, 60],
       [50, 54, 74],
       [ 9, 31, 53],
       [15, 23, 59],
       [ 4, 56, 72],
       [14, 29, 38]])

$A$, $B$, $C$를 아래와 같이 정의하세요.

\begin{align*}
 A&= 
\begin{pmatrix}
1 &2  &1 \\ 
2 &1 & 1\\ 
-1 & 0 & 1
\end{pmatrix}
\end{align*}

\begin{align*}
 B&= 
\begin{pmatrix}
1 &0 \\ 
0 &1 \\ 
1 & 0 
\end{pmatrix}
\end{align*}

\begin{align*}
 C&= 
\begin{pmatrix}
1 \\ 
0  \\ 
-1  
\end{pmatrix}
\end{align*}



In [ ]:
A = np.array([[1,2,1],[2,1,1],[-1,0,1]])
B = np.array([[1,0],[0,1],[1,0]])
C = np.array([[1],[0],[-1]])

A,B,C

(array([[ 1,  2,  1],
        [ 2,  1,  1],
        [-1,  0,  1]]),
 array([[1, 0],
        [0, 1],
        [1, 0]]),
 array([[ 1],
        [ 0],
        [-1]]))

**예제 15**


$A$, $B$ 의 행렬곱

In [ ]:
A @ B

array([[2, 2],
       [3, 1],
       [0, 0]])

**예제 16**


$A$, $C$ 의 행렬곱

In [ ]:
A @ C

array([[ 0],
       [ 1],
       [-2]])

**예제 17**


$A * C$

In [ ]:
A * C

array([[ 1,  2,  1],
       [ 0,  0,  0],
       [ 1,  0, -1]])

**예제 18**


$B$와 $B^T$의 내적

In [ ]:
np.dot(B,B.T)

array([[1, 0, 1],
       [0, 1, 0],
       [1, 0, 1]])


20명의 학생의 번호와, 키와, 수행평가 점수가 아래와 같이 정의 되어 있습니다. 

```
idx = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]
tall = [178, 171, 179, 173, 152, 157, 175, 180, 182, 165, 160, 164, 174, 163, 158, 159, 172, 155, 177, 162]
score = [57, 64, 85, 30, 58, 72, 84, 63, 49, 94, 70, 54, 60, 68, 74, 78, 92, 86, 51, 37]
```


In [ ]:
idx = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
tall = np.array([178, 171, 179, 173, 152, 157, 175, 180, 182, 165, 160, 164, 174, 163, 158, 159, 172, 155, 177, 162])
score = np.array([57, 64, 85, 30, 58, 72, 84, 63, 49, 94, 70, 54, 60, 68, 74, 78, 92, 86, 51, 37])

**예제 19**

키가 큰 순으로 학생들의 번호(idx)를 정렬하세요.



In [ ]:
temp_tall = np.argsort(tall)
print(idx[temp_tall])
# np.sort([temp_tall], axis = 0)

[ 9  8  3  1 19  7 13  4 17  2 10 12 14 20 11 16 15  6 18  5]


**예제 20**

수행평가 점수가 낮은 순으로 학생들의 번호(idx)를 정렬하세요.


In [ ]:
temp_score = np.argsort(score)
print(idx[temp_score])

[ 4 20  9 19 12  1  5 13  8  2 14 11  6 15 16  7  3 18 17 10]
